// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package freespacecmd

import (
	"github.com/Duansg/freespace/manager/base/conf"
	"github.com/Duansg/freespace/manager/base/data"
	"github.com/Duansg/freespace/manager/base/handler"
	"github.com/Duansg/freespace/manager/router"
	"github.com/Duansg/freespace/manager/server"
	"github.com/Duansg/freespace/manager/service"
	"github.com/Duansg/freespace/manager/service/config"
	"github.com/segmentfault/pacman"
	"github.com/segmentfault/pacman/log"
)

// Injectors from wire.go:

// initApplication init application.
func initApplication(debug bool, serverConf *conf.Server, dbConf *data.Database, swaggerConf *router.SwaggerConfig, serviceConf *service_config.ServiceConfig, logConf log.Logger) (*pacman.Application, func(), error) {
	staticRouter := router.NewStaticRouter(serviceConf)
	engine, err := data.NewDB(debug, dbConf)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(engine)
	if err != nil {
		return nil, nil, err
	}
	articleMapper := data.NewArticleMapper(dataData)
	articleService := service.NewArticleService(articleMapper)
	articleHandler := handler.NewArticleHandler(articleService)
	menuMapper := data.NewMenuMapper(dataData)
	menuService := service.NewMenuService(menuMapper)
	menuHandler := handler.NewMenuHandler(menuService)
	userMapper := data.NewUserMapper(dataData)
	userService := service.NewUserService(userMapper)
	userHandler := handler.NewUserHandler(userService)
	routerRouter := router.NewRouter(articleHandler, menuHandler, userHandler)
	ginEngine := server.NewHTTPServer(debug, staticRouter, routerRouter)
	application := newApplication(serverConf, ginEngine)
	return application, func() {
		cleanup()
	}, nil
}
